--Q1_2022_num_rides
SELECT COUNT(*) as Q1_2022_num_rides
FROM `diesel-equator-385617.divvy2.Q1_2022_length_weekday`
--Q2_2022_num_rides
SELECT COUNT(*) as Q2_2022_num_rides
FROM `diesel-equator-385617.divvy2.Q1_2022_length_weekday`
--Q3_2022_num_rides
SELECT COUNT(*) as Q3_2022_num_rides
FROM `diesel-equator-385617.divvy2.Q1_2022_length_weekday`
--Q4_2022_num_rides
SELECT COUNT(*) as Q4_2022_num_rides
FROM `diesel-equator-385617.divvy2.Q1_2022_length_weekday`
